name: Publish to Winget
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest # Action can only run on Windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: sharkdp.fd
          installers-regex: '-pc-windows-msvc\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
